# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  param_fetcher_listener:  true
  #    allowed_methods_listener:  true
  #    routing_loader: true
  view:
    formats: {json: true, xml: false}
    view_response_listener: true
  exception:
    exception_controller: 'fos_rest.exception.controller:showAction'
  serializer:
    serialize_null: true
  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: validationErrors
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
  format_listener:
    rules:
      - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
      - { path: ^/, priorities: [ 'html', '*/*'], fallback_format: ~, prefer_extension: true }
